from __future__ import annotations

TEMPLATES = [
    {
        "id": "crm",
        "name": "CRM",
        "description": "Customer relationship management with leads, contacts, deals, and activities.",
        "icon": "Users",
        "color": "#6366f1",
        "category": "sales",
        "tags": ["sales", "crm", "leads"],
        "app": {
            "name": "CRM",
            "slug": "crm",
            "description": "Customer relationship management",
            "icon": "Users",
            "color": "#6366f1",
        },
        "models": [
            {
                "name": "Contacts",
                "slug": "contacts",
                "plural_name": "Contacts",
                "icon": "User",
                "fields": [
                    {"name": "full_name", "label": "Full Name", "type": "text", "order": 0, "is_required": True, "is_searchable": True},
                    {"name": "email", "label": "Email", "type": "email", "order": 1, "is_required": True},
                    {"name": "phone", "label": "Phone", "type": "phone", "order": 2},
                    {"name": "company", "label": "Company", "type": "text", "order": 3, "is_searchable": True},
                    {"name": "status", "label": "Status", "type": "select", "order": 4,
                     "config": {"options": ["Lead", "Prospect", "Customer", "Churned"]}},
                    {"name": "notes", "label": "Notes", "type": "rich_text", "order": 5},
                ],
            },
            {
                "name": "Deals",
                "slug": "deals",
                "plural_name": "Deals",
                "icon": "DollarSign",
                "fields": [
                    {"name": "title", "label": "Deal Title", "type": "text", "order": 0, "is_required": True, "is_searchable": True},
                    {"name": "value", "label": "Value ($)", "type": "currency", "order": 1},
                    {"name": "stage", "label": "Stage", "type": "select", "order": 2,
                     "config": {"options": ["Prospecting", "Qualification", "Proposal", "Negotiation", "Closed Won", "Closed Lost"]}},
                    {"name": "close_date", "label": "Expected Close", "type": "date", "order": 3},
                    {"name": "probability", "label": "Probability (%)", "type": "number", "order": 4},
                    {"name": "notes", "label": "Notes", "type": "rich_text", "order": 5},
                ],
            },
            {
                "name": "Activities",
                "slug": "activities",
                "plural_name": "Activities",
                "icon": "Activity",
                "fields": [
                    {"name": "subject", "label": "Subject", "type": "text", "order": 0, "is_required": True},
                    {"name": "type", "label": "Type", "type": "select", "order": 1,
                     "config": {"options": ["Call", "Email", "Meeting", "Task", "Note"]}},
                    {"name": "due_date", "label": "Due Date", "type": "datetime", "order": 2},
                    {"name": "status", "label": "Status", "type": "select", "order": 3,
                     "config": {"options": ["Planned", "Completed", "Cancelled"]}},
                ],
            },
        ],
    },
    {
        "id": "inventory",
        "name": "Inventory Management",
        "description": "Track products, stock levels, suppliers, and purchase orders.",
        "icon": "Package",
        "color": "#10b981",
        "category": "operations",
        "tags": ["inventory", "warehouse", "products"],
        "app": {
            "name": "Inventory",
            "slug": "inventory",
            "description": "Product and stock management",
            "icon": "Package",
            "color": "#10b981",
        },
        "models": [
            {
                "name": "Products",
                "slug": "products",
                "plural_name": "Products",
                "icon": "Box",
                "fields": [
                    {"name": "name", "label": "Product Name", "type": "text", "order": 0, "is_required": True, "is_searchable": True},
                    {"name": "sku", "label": "SKU", "type": "text", "order": 1},
                    {"name": "category", "label": "Category", "type": "select", "order": 2,
                     "config": {"options": ["Electronics", "Clothing", "Food", "Hardware", "Other"]}},
                    {"name": "unit_price", "label": "Unit Price", "type": "currency", "order": 3},
                    {"name": "stock_quantity", "label": "Stock Qty", "type": "number", "order": 4},
                    {"name": "reorder_point", "label": "Reorder Point", "type": "number", "order": 5},
                    {"name": "supplier", "label": "Supplier", "type": "text", "order": 6},
                ],
            },
            {
                "name": "Purchase Orders",
                "slug": "purchase_orders",
                "plural_name": "Purchase Orders",
                "icon": "ShoppingCart",
                "fields": [
                    {"name": "order_number", "label": "Order #", "type": "text", "order": 0, "is_required": True},
                    {"name": "supplier", "label": "Supplier", "type": "text", "order": 1},
                    {"name": "status", "label": "Status", "type": "select", "order": 2,
                     "config": {"options": ["Draft", "Sent", "Confirmed", "Received", "Cancelled"]}},
                    {"name": "order_date", "label": "Order Date", "type": "date", "order": 3},
                    {"name": "expected_date", "label": "Expected Date", "type": "date", "order": 4},
                    {"name": "total_amount", "label": "Total Amount", "type": "currency", "order": 5},
                    {"name": "notes", "label": "Notes", "type": "text", "order": 6},
                ],
            },
        ],
    },
    {
        "id": "project_management",
        "name": "Project Management",
        "description": "Manage projects, tasks, milestones, and team workload.",
        "icon": "Kanban",
        "color": "#f59e0b",
        "category": "productivity",
        "tags": ["projects", "tasks", "team"],
        "app": {
            "name": "Projects",
            "slug": "projects",
            "description": "Project and task tracking",
            "icon": "Kanban",
            "color": "#f59e0b",
        },
        "models": [
            {
                "name": "Projects",
                "slug": "projects",
                "plural_name": "Projects",
                "icon": "FolderOpen",
                "fields": [
                    {"name": "name", "label": "Project Name", "type": "text", "order": 0, "is_required": True, "is_searchable": True},
                    {"name": "status", "label": "Status", "type": "select", "order": 1,
                     "config": {"options": ["Planning", "Active", "On Hold", "Completed", "Cancelled"]}},
                    {"name": "priority", "label": "Priority", "type": "select", "order": 2,
                     "config": {"options": ["Low", "Medium", "High", "Critical"]}},
                    {"name": "start_date", "label": "Start Date", "type": "date", "order": 3},
                    {"name": "due_date", "label": "Due Date", "type": "date", "order": 4},
                    {"name": "budget", "label": "Budget", "type": "currency", "order": 5},
                    {"name": "description", "label": "Description", "type": "rich_text", "order": 6},
                ],
            },
            {
                "name": "Tasks",
                "slug": "tasks",
                "plural_name": "Tasks",
                "icon": "CheckSquare",
                "fields": [
                    {"name": "title", "label": "Task Title", "type": "text", "order": 0, "is_required": True, "is_searchable": True},
                    {"name": "status", "label": "Status", "type": "select", "order": 1,
                     "config": {"options": ["Backlog", "To Do", "In Progress", "Review", "Done"]}},
                    {"name": "priority", "label": "Priority", "type": "select", "order": 2,
                     "config": {"options": ["Low", "Medium", "High"]}},
                    {"name": "due_date", "label": "Due Date", "type": "date", "order": 3},
                    {"name": "estimated_hours", "label": "Est. Hours", "type": "number", "order": 4},
                    {"name": "description", "label": "Description", "type": "rich_text", "order": 5},
                ],
            },
        ],
    },
    {
        "id": "hr",
        "name": "HR & People Ops",
        "description": "Employee directory, onboarding checklists, leave requests, and performance reviews.",
        "icon": "UserCheck",
        "color": "#8b5cf6",
        "category": "hr",
        "tags": ["hr", "employees", "leave"],
        "app": {
            "name": "HR",
            "slug": "hr",
            "description": "Human resources and people operations",
            "icon": "UserCheck",
            "color": "#8b5cf6",
        },
        "models": [
            {
                "name": "Employees",
                "slug": "employees",
                "plural_name": "Employees",
                "icon": "Users",
                "fields": [
                    {"name": "full_name", "label": "Full Name", "type": "text", "order": 0, "is_required": True, "is_searchable": True},
                    {"name": "email", "label": "Email", "type": "email", "order": 1},
                    {"name": "department", "label": "Department", "type": "select", "order": 2,
                     "config": {"options": ["Engineering", "Sales", "Marketing", "HR", "Finance", "Operations"]}},
                    {"name": "role", "label": "Role / Title", "type": "text", "order": 3},
                    {"name": "employment_type", "label": "Employment Type", "type": "select", "order": 4,
                     "config": {"options": ["Full-Time", "Part-Time", "Contractor", "Intern"]}},
                    {"name": "start_date", "label": "Start Date", "type": "date", "order": 5},
                    {"name": "salary", "label": "Salary", "type": "currency", "order": 6},
                    {"name": "status", "label": "Status", "type": "select", "order": 7,
                     "config": {"options": ["Active", "On Leave", "Terminated"]}},
                ],
            },
            {
                "name": "Leave Requests",
                "slug": "leave_requests",
                "plural_name": "Leave Requests",
                "icon": "Calendar",
                "fields": [
                    {"name": "employee_name", "label": "Employee", "type": "text", "order": 0, "is_required": True},
                    {"name": "leave_type", "label": "Leave Type", "type": "select", "order": 1,
                     "config": {"options": ["Annual", "Sick", "Maternity/Paternity", "Unpaid", "Other"]}},
                    {"name": "start_date", "label": "Start Date", "type": "date", "order": 2, "is_required": True},
                    {"name": "end_date", "label": "End Date", "type": "date", "order": 3, "is_required": True},
                    {"name": "status", "label": "Status", "type": "select", "order": 4,
                     "config": {"options": ["Pending", "Approved", "Rejected"]}},
                    {"name": "reason", "label": "Reason", "type": "text", "order": 5},
                ],
            },
        ],
    },
    {
        "id": "finance",
        "name": "Finance Tracker",
        "description": "Track expenses, income, budgets, and generate financial summaries.",
        "icon": "DollarSign",
        "color": "#22d3ee",
        "category": "finance",
        "tags": ["finance", "expenses", "budget"],
        "app": {
            "name": "Finance",
            "slug": "finance",
            "description": "Expense and income tracking",
            "icon": "DollarSign",
            "color": "#22d3ee",
        },
        "models": [
            {
                "name": "Transactions",
                "slug": "transactions",
                "plural_name": "Transactions",
                "icon": "Receipt",
                "fields": [
                    {"name": "description", "label": "Description", "type": "text", "order": 0, "is_required": True, "is_searchable": True},
                    {"name": "amount", "label": "Amount", "type": "currency", "order": 1, "is_required": True},
                    {"name": "type", "label": "Type", "type": "select", "order": 2,
                     "config": {"options": ["Income", "Expense"]}},
                    {"name": "category", "label": "Category", "type": "select", "order": 3,
                     "config": {"options": ["Salary", "Sales", "Rent", "Utilities", "Marketing", "Travel", "Office", "Other"]}},
                    {"name": "date", "label": "Date", "type": "date", "order": 4, "is_required": True},
                    {"name": "payment_method", "label": "Payment Method", "type": "select", "order": 5,
                     "config": {"options": ["Cash", "Bank Transfer", "Credit Card", "UPI", "Cheque"]}},
                    {"name": "reference", "label": "Reference #", "type": "text", "order": 6},
                    {"name": "receipt", "label": "Receipt", "type": "file", "order": 7},
                ],
            },
            {
                "name": "Budgets",
                "slug": "budgets",
                "plural_name": "Budgets",
                "icon": "PieChart",
                "fields": [
                    {"name": "category", "label": "Category", "type": "text", "order": 0, "is_required": True},
                    {"name": "period", "label": "Period", "type": "select", "order": 1,
                     "config": {"options": ["Monthly", "Quarterly", "Annual"]}},
                    {"name": "budgeted_amount", "label": "Budgeted", "type": "currency", "order": 2},
                    {"name": "fiscal_year", "label": "Fiscal Year", "type": "number", "order": 3},
                ],
            },
        ],
    },
    {
        "id": "helpdesk",
        "name": "Help Desk",
        "description": "Customer support tickets, issue tracking, and SLA management.",
        "icon": "HeadphonesIcon",
        "color": "#ef4444",
        "category": "support",
        "tags": ["support", "tickets", "helpdesk"],
        "app": {
            "name": "Help Desk",
            "slug": "helpdesk",
            "description": "Customer support and ticket management",
            "icon": "Headphones",
            "color": "#ef4444",
        },
        "models": [
            {
                "name": "Tickets",
                "slug": "tickets",
                "plural_name": "Tickets",
                "icon": "Ticket",
                "fields": [
                    {"name": "subject", "label": "Subject", "type": "text", "order": 0, "is_required": True, "is_searchable": True},
                    {"name": "description", "label": "Description", "type": "rich_text", "order": 1},
                    {"name": "status", "label": "Status", "type": "select", "order": 2,
                     "config": {"options": ["Open", "In Progress", "Pending Customer", "Resolved", "Closed"]}},
                    {"name": "priority", "label": "Priority", "type": "select", "order": 3,
                     "config": {"options": ["Low", "Medium", "High", "Critical"]}},
                    {"name": "category", "label": "Category", "type": "select", "order": 4,
                     "config": {"options": ["Technical", "Billing", "General", "Feature Request", "Bug"]}},
                    {"name": "customer_email", "label": "Customer Email", "type": "email", "order": 5},
                    {"name": "created_date", "label": "Created", "type": "datetime", "order": 6},
                    {"name": "resolved_date", "label": "Resolved", "type": "datetime", "order": 7},
                ],
            },
            {
                "name": "Knowledge Base",
                "slug": "knowledge_base",
                "plural_name": "Knowledge Base",
                "icon": "BookOpen",
                "fields": [
                    {"name": "title", "label": "Article Title", "type": "text", "order": 0, "is_required": True, "is_searchable": True},
                    {"name": "category", "label": "Category", "type": "select", "order": 1,
                     "config": {"options": ["Getting Started", "Billing", "Technical", "FAQs"]}},
                    {"name": "content", "label": "Content", "type": "rich_text", "order": 2},
                    {"name": "status", "label": "Status", "type": "select", "order": 3,
                     "config": {"options": ["Draft", "Published", "Archived"]}},
                ],
            },
        ],
    },
]

TEMPLATE_BY_ID = {t["id"]: t for t in TEMPLATES}
