from __future__ import annotations

import io
from datetime import datetime, timezone
from typing import Any

from fastapi.responses import StreamingResponse

from apps.schema_engine.repository import get_model_by_slug
from apps.schema_engine.service import list_records


async def generate_pdf_report(
    model_slug: str,
    app_id: str,
    tenant_id: str,
    title: str | None = None,
) -> StreamingResponse:
    """Generate a PDF report of all records in a model."""
    try:
        from fpdf import FPDF
    except ImportError:
        from fastapi import HTTPException
        raise HTTPException(
            status_code=501,
            detail="PDF generation requires 'fpdf2' package. Run: pip install fpdf2",
        )

    model = await get_model_by_slug(model_slug, app_id)
    if model is None:
        from core.exceptions import NotFoundError
        raise NotFoundError("Model", model_slug)

    # Collect all records (paginate through)
    all_records: list[dict] = []
    page = 1
    while True:
        result = await list_records(
            model_slug=model_slug, app_id=app_id, tenant_id=tenant_id,
            page=page, page_size=500, sort_field="created_at", sort_dir=-1,
        )
        all_records.extend(result.items)
        if not result.has_more:
            break
        page += 1

    # Determine columns (skip FORMULA and CHILD_TABLE, keep first 6 for readability)
    from apps.schema_engine.models import FieldType
    exportable_fields = [
        f for f in sorted(model.fields, key=lambda x: x.order)
        if f.type not in (FieldType.FORMULA, FieldType.CHILD_TABLE)
    ][:6]
    field_names = [f.name for f in exportable_fields]
    field_labels = [f.label or f.name for f in exportable_fields]

    report_title = title or f"{model.plural_name or model.name} Report"
    generated_at = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # Build PDF
    pdf = FPDF(orientation="L", unit="mm", format="A4")  # Landscape for more columns
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, report_title, ln=True, align="C")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 6, f"Generated: {generated_at}  |  Total records: {len(all_records)}", ln=True, align="C")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    # Table
    page_width = pdf.w - 2 * pdf.l_margin
    n_cols = len(field_names)
    col_w = page_width / n_cols if n_cols > 0 else page_width

    # Header row
    pdf.set_fill_color(79, 70, 229)   # indigo-600
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 9)
    for label in field_labels:
        pdf.cell(col_w, 8, _truncate(label, 20), border=0, fill=True, align="C")
    pdf.ln()
    pdf.set_text_color(0, 0, 0)

    # Data rows
    pdf.set_font("Helvetica", "", 8)
    for i, rec in enumerate(all_records):
        data = rec.get("data", rec)
        fill = i % 2 == 0
        if fill:
            pdf.set_fill_color(245, 245, 255)
        for fname in field_names:
            val = data.get(fname, "")
            if isinstance(val, list):
                val = ", ".join(str(v) for v in val)
            elif isinstance(val, dict):
                val = val.get("filename") or str(val)
            elif val is None:
                val = ""
            else:
                val = str(val)
            pdf.cell(col_w, 7, _truncate(val, 28), border=0, fill=fill)
        pdf.ln()

    # Footer line
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 5, "Generated by Stackless No-Code Platform", align="C")

    # Output
    buf = io.BytesIO(pdf.output())
    buf.seek(0)
    filename = f"{model_slug}_report.pdf"
    return StreamingResponse(
        iter([buf.read()]),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


def _truncate(text: str, max_len: int) -> str:
    text = text.strip()
    return text[:max_len - 1] + "\u2026" if len(text) > max_len else text
