/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkflowTemplatesRouteImport } from './routes/_authenticated/workflow-templates'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedScriptsRouteImport } from './routes/_authenticated/scripts'
import { Route as AuthenticatedRulesRouteImport } from './routes/_authenticated/rules'
import { Route as AuthenticatedPrintFormatsRouteImport } from './routes/_authenticated/print-formats'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedEmailInboxRouteImport } from './routes/_authenticated/email-inbox'
import { Route as AuthenticatedEmailCampaignsRouteImport } from './routes/_authenticated/email-campaigns'
import { Route as AuthenticatedDeskChatRouteImport } from './routes/_authenticated/desk-chat'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedApiKeysRouteImport } from './routes/_authenticated/api-keys'
import { Route as AuthenticatedAiBuilderRouteImport } from './routes/_authenticated/ai-builder'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as PortalTenantIdMySubmissionsRouteImport } from './routes/portal.$tenantId.my-submissions'
import { Route as PortalTenantIdLoginRouteImport } from './routes/portal.$tenantId.login'
import { Route as FormsTenantIdFormSlugRouteImport } from './routes/forms.$tenantId.$formSlug'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings/security'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings/profile'
import { Route as AuthenticatedSettingsLetterHeadsRouteImport } from './routes/_authenticated/settings/letter-heads'
import { Route as AuthenticatedPortalAppIdRouteImport } from './routes/_authenticated/portal/$appId'
import { Route as AuthenticatedApprovalsInboxRouteImport } from './routes/_authenticated/approvals/inbox'
import { Route as AuthenticatedApprovalsFlowsRouteImport } from './routes/_authenticated/approvals/flows'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminUsageRouteImport } from './routes/_authenticated/admin/usage'
import { Route as AuthenticatedAdminTenantsRouteImport } from './routes/_authenticated/admin/tenants'
import { Route as AuthenticatedAdminRoleProfilesRouteImport } from './routes/_authenticated/admin/role-profiles'
import { Route as AuthenticatedAdminRequestLogsRouteImport } from './routes/_authenticated/admin/request-logs'
import { Route as AuthenticatedAdminRbacRouteImport } from './routes/_authenticated/admin/rbac'
import { Route as AuthenticatedAdminPropertySetterRouteImport } from './routes/_authenticated/admin/property-setter'
import { Route as AuthenticatedAdminJobsRouteImport } from './routes/_authenticated/admin/jobs'
import { Route as AuthenticatedAdminFilesRouteImport } from './routes/_authenticated/admin/files'
import { Route as AuthenticatedAdminErrorLogsRouteImport } from './routes/_authenticated/admin/error-logs'
import { Route as AuthenticatedAdminConsoleRouteImport } from './routes/_authenticated/admin/console'
import { Route as AuthenticatedAdminBackupRouteImport } from './routes/_authenticated/admin/backup'
import { Route as AuthenticatedAdminAuditLogsRouteImport } from './routes/_authenticated/admin/audit-logs'
import { Route as AuthenticatedAdminAiConfigRouteImport } from './routes/_authenticated/admin/ai-config'
import { Route as AuthenticatedWorkflowsRunsIndexRouteImport } from './routes/_authenticated/workflows/runs/index'
import { Route as AuthenticatedAppsAppIdIndexRouteImport } from './routes/_authenticated/apps/$appId/index'
import { Route as AuthenticatedWorkflowsRunsRunIdRouteImport } from './routes/_authenticated/workflows/runs/$runId'
import { Route as AuthenticatedAppsAppIdScriptsRouteImport } from './routes/_authenticated/apps/$appId/scripts'
import { Route as AuthenticatedAppsAppIdReportsRouteImport } from './routes/_authenticated/apps/$appId/reports'
import { Route as AuthenticatedAppsAppIdRecordsRouteImport } from './routes/_authenticated/apps/$appId/records'
import { Route as AuthenticatedAppsAppIdFlowRouteImport } from './routes/_authenticated/apps/$appId/flow'
import { Route as AuthenticatedAppsAppIdBuilderRouteImport } from './routes/_authenticated/apps/$appId/builder'
import { Route as AuthenticatedAppsAppIdModelSlugRecordsRecordIdRouteImport } from './routes/_authenticated/apps/$appId/$modelSlug/records/$recordId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkflowTemplatesRoute =
  AuthenticatedWorkflowTemplatesRouteImport.update({
    id: '/workflow-templates',
    path: '/workflow-templates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScriptsRoute = AuthenticatedScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRulesRoute = AuthenticatedRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPrintFormatsRoute =
  AuthenticatedPrintFormatsRouteImport.update({
    id: '/print-formats',
    path: '/print-formats',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmailInboxRoute = AuthenticatedEmailInboxRouteImport.update({
  id: '/email-inbox',
  path: '/email-inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmailCampaignsRoute =
  AuthenticatedEmailCampaignsRouteImport.update({
    id: '/email-campaigns',
    path: '/email-campaigns',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDeskChatRoute = AuthenticatedDeskChatRouteImport.update({
  id: '/desk-chat',
  path: '/desk-chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApiKeysRoute = AuthenticatedApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiBuilderRoute = AuthenticatedAiBuilderRouteImport.update({
  id: '/ai-builder',
  path: '/ai-builder',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PortalTenantIdMySubmissionsRoute =
  PortalTenantIdMySubmissionsRouteImport.update({
    id: '/portal/$tenantId/my-submissions',
    path: '/portal/$tenantId/my-submissions',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalTenantIdLoginRoute = PortalTenantIdLoginRouteImport.update({
  id: '/portal/$tenantId/login',
  path: '/portal/$tenantId/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsTenantIdFormSlugRoute = FormsTenantIdFormSlugRouteImport.update({
  id: '/forms/$tenantId/$formSlug',
  path: '/forms/$tenantId/$formSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/settings/security',
    path: '/settings/security',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsLetterHeadsRoute =
  AuthenticatedSettingsLetterHeadsRouteImport.update({
    id: '/settings/letter-heads',
    path: '/settings/letter-heads',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortalAppIdRoute =
  AuthenticatedPortalAppIdRouteImport.update({
    id: '/portal/$appId',
    path: '/portal/$appId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApprovalsInboxRoute =
  AuthenticatedApprovalsInboxRouteImport.update({
    id: '/approvals/inbox',
    path: '/approvals/inbox',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApprovalsFlowsRoute =
  AuthenticatedApprovalsFlowsRouteImport.update({
    id: '/approvals/flows',
    path: '/approvals/flows',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminUsageRoute = AuthenticatedAdminUsageRouteImport.update({
  id: '/admin/usage',
  path: '/admin/usage',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminTenantsRoute =
  AuthenticatedAdminTenantsRouteImport.update({
    id: '/admin/tenants',
    path: '/admin/tenants',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoleProfilesRoute =
  AuthenticatedAdminRoleProfilesRouteImport.update({
    id: '/admin/role-profiles',
    path: '/admin/role-profiles',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRequestLogsRoute =
  AuthenticatedAdminRequestLogsRouteImport.update({
    id: '/admin/request-logs',
    path: '/admin/request-logs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRbacRoute = AuthenticatedAdminRbacRouteImport.update({
  id: '/admin/rbac',
  path: '/admin/rbac',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminPropertySetterRoute =
  AuthenticatedAdminPropertySetterRouteImport.update({
    id: '/admin/property-setter',
    path: '/admin/property-setter',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminJobsRoute = AuthenticatedAdminJobsRouteImport.update({
  id: '/admin/jobs',
  path: '/admin/jobs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminFilesRoute = AuthenticatedAdminFilesRouteImport.update({
  id: '/admin/files',
  path: '/admin/files',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminErrorLogsRoute =
  AuthenticatedAdminErrorLogsRouteImport.update({
    id: '/admin/error-logs',
    path: '/admin/error-logs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminConsoleRoute =
  AuthenticatedAdminConsoleRouteImport.update({
    id: '/admin/console',
    path: '/admin/console',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBackupRoute =
  AuthenticatedAdminBackupRouteImport.update({
    id: '/admin/backup',
    path: '/admin/backup',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAuditLogsRoute =
  AuthenticatedAdminAuditLogsRouteImport.update({
    id: '/admin/audit-logs',
    path: '/admin/audit-logs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAiConfigRoute =
  AuthenticatedAdminAiConfigRouteImport.update({
    id: '/admin/ai-config',
    path: '/admin/ai-config',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkflowsRunsIndexRoute =
  AuthenticatedWorkflowsRunsIndexRouteImport.update({
    id: '/workflows/runs/',
    path: '/workflows/runs/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsAppIdIndexRoute =
  AuthenticatedAppsAppIdIndexRouteImport.update({
    id: '/apps/$appId/',
    path: '/apps/$appId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkflowsRunsRunIdRoute =
  AuthenticatedWorkflowsRunsRunIdRouteImport.update({
    id: '/workflows/runs/$runId',
    path: '/workflows/runs/$runId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsAppIdScriptsRoute =
  AuthenticatedAppsAppIdScriptsRouteImport.update({
    id: '/apps/$appId/scripts',
    path: '/apps/$appId/scripts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsAppIdReportsRoute =
  AuthenticatedAppsAppIdReportsRouteImport.update({
    id: '/apps/$appId/reports',
    path: '/apps/$appId/reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsAppIdRecordsRoute =
  AuthenticatedAppsAppIdRecordsRouteImport.update({
    id: '/apps/$appId/records',
    path: '/apps/$appId/records',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsAppIdFlowRoute =
  AuthenticatedAppsAppIdFlowRouteImport.update({
    id: '/apps/$appId/flow',
    path: '/apps/$appId/flow',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsAppIdBuilderRoute =
  AuthenticatedAppsAppIdBuilderRouteImport.update({
    id: '/apps/$appId/builder',
    path: '/apps/$appId/builder',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsAppIdModelSlugRecordsRecordIdRoute =
  AuthenticatedAppsAppIdModelSlugRecordsRecordIdRouteImport.update({
    id: '/apps/$appId/$modelSlug/records/$recordId',
    path: '/apps/$appId/$modelSlug/records/$recordId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ai-builder': typeof AuthenticatedAiBuilderRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/desk-chat': typeof AuthenticatedDeskChatRoute
  '/email-campaigns': typeof AuthenticatedEmailCampaignsRoute
  '/email-inbox': typeof AuthenticatedEmailInboxRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/print-formats': typeof AuthenticatedPrintFormatsRoute
  '/rules': typeof AuthenticatedRulesRoute
  '/scripts': typeof AuthenticatedScriptsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/workflow-templates': typeof AuthenticatedWorkflowTemplatesRoute
  '/admin/ai-config': typeof AuthenticatedAdminAiConfigRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/console': typeof AuthenticatedAdminConsoleRoute
  '/admin/error-logs': typeof AuthenticatedAdminErrorLogsRoute
  '/admin/files': typeof AuthenticatedAdminFilesRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/property-setter': typeof AuthenticatedAdminPropertySetterRoute
  '/admin/rbac': typeof AuthenticatedAdminRbacRoute
  '/admin/request-logs': typeof AuthenticatedAdminRequestLogsRoute
  '/admin/role-profiles': typeof AuthenticatedAdminRoleProfilesRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/approvals/flows': typeof AuthenticatedApprovalsFlowsRoute
  '/approvals/inbox': typeof AuthenticatedApprovalsInboxRoute
  '/portal/$appId': typeof AuthenticatedPortalAppIdRoute
  '/settings/letter-heads': typeof AuthenticatedSettingsLetterHeadsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/forms/$tenantId/$formSlug': typeof FormsTenantIdFormSlugRoute
  '/portal/$tenantId/login': typeof PortalTenantIdLoginRoute
  '/portal/$tenantId/my-submissions': typeof PortalTenantIdMySubmissionsRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/apps/$appId/builder': typeof AuthenticatedAppsAppIdBuilderRoute
  '/apps/$appId/flow': typeof AuthenticatedAppsAppIdFlowRoute
  '/apps/$appId/records': typeof AuthenticatedAppsAppIdRecordsRoute
  '/apps/$appId/reports': typeof AuthenticatedAppsAppIdReportsRoute
  '/apps/$appId/scripts': typeof AuthenticatedAppsAppIdScriptsRoute
  '/workflows/runs/$runId': typeof AuthenticatedWorkflowsRunsRunIdRoute
  '/apps/$appId/': typeof AuthenticatedAppsAppIdIndexRoute
  '/workflows/runs/': typeof AuthenticatedWorkflowsRunsIndexRoute
  '/apps/$appId/$modelSlug/records/$recordId': typeof AuthenticatedAppsAppIdModelSlugRecordsRecordIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ai-builder': typeof AuthenticatedAiBuilderRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/desk-chat': typeof AuthenticatedDeskChatRoute
  '/email-campaigns': typeof AuthenticatedEmailCampaignsRoute
  '/email-inbox': typeof AuthenticatedEmailInboxRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/print-formats': typeof AuthenticatedPrintFormatsRoute
  '/rules': typeof AuthenticatedRulesRoute
  '/scripts': typeof AuthenticatedScriptsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/workflow-templates': typeof AuthenticatedWorkflowTemplatesRoute
  '/admin/ai-config': typeof AuthenticatedAdminAiConfigRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/console': typeof AuthenticatedAdminConsoleRoute
  '/admin/error-logs': typeof AuthenticatedAdminErrorLogsRoute
  '/admin/files': typeof AuthenticatedAdminFilesRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/property-setter': typeof AuthenticatedAdminPropertySetterRoute
  '/admin/rbac': typeof AuthenticatedAdminRbacRoute
  '/admin/request-logs': typeof AuthenticatedAdminRequestLogsRoute
  '/admin/role-profiles': typeof AuthenticatedAdminRoleProfilesRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/approvals/flows': typeof AuthenticatedApprovalsFlowsRoute
  '/approvals/inbox': typeof AuthenticatedApprovalsInboxRoute
  '/portal/$appId': typeof AuthenticatedPortalAppIdRoute
  '/settings/letter-heads': typeof AuthenticatedSettingsLetterHeadsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/forms/$tenantId/$formSlug': typeof FormsTenantIdFormSlugRoute
  '/portal/$tenantId/login': typeof PortalTenantIdLoginRoute
  '/portal/$tenantId/my-submissions': typeof PortalTenantIdMySubmissionsRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/apps/$appId/builder': typeof AuthenticatedAppsAppIdBuilderRoute
  '/apps/$appId/flow': typeof AuthenticatedAppsAppIdFlowRoute
  '/apps/$appId/records': typeof AuthenticatedAppsAppIdRecordsRoute
  '/apps/$appId/reports': typeof AuthenticatedAppsAppIdReportsRoute
  '/apps/$appId/scripts': typeof AuthenticatedAppsAppIdScriptsRoute
  '/workflows/runs/$runId': typeof AuthenticatedWorkflowsRunsRunIdRoute
  '/apps/$appId': typeof AuthenticatedAppsAppIdIndexRoute
  '/workflows/runs': typeof AuthenticatedWorkflowsRunsIndexRoute
  '/apps/$appId/$modelSlug/records/$recordId': typeof AuthenticatedAppsAppIdModelSlugRecordsRecordIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/ai-builder': typeof AuthenticatedAiBuilderRoute
  '/_authenticated/api-keys': typeof AuthenticatedApiKeysRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/desk-chat': typeof AuthenticatedDeskChatRoute
  '/_authenticated/email-campaigns': typeof AuthenticatedEmailCampaignsRoute
  '/_authenticated/email-inbox': typeof AuthenticatedEmailInboxRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/print-formats': typeof AuthenticatedPrintFormatsRoute
  '/_authenticated/rules': typeof AuthenticatedRulesRoute
  '/_authenticated/scripts': typeof AuthenticatedScriptsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/workflow-templates': typeof AuthenticatedWorkflowTemplatesRoute
  '/_authenticated/admin/ai-config': typeof AuthenticatedAdminAiConfigRoute
  '/_authenticated/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/_authenticated/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/_authenticated/admin/console': typeof AuthenticatedAdminConsoleRoute
  '/_authenticated/admin/error-logs': typeof AuthenticatedAdminErrorLogsRoute
  '/_authenticated/admin/files': typeof AuthenticatedAdminFilesRoute
  '/_authenticated/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/_authenticated/admin/property-setter': typeof AuthenticatedAdminPropertySetterRoute
  '/_authenticated/admin/rbac': typeof AuthenticatedAdminRbacRoute
  '/_authenticated/admin/request-logs': typeof AuthenticatedAdminRequestLogsRoute
  '/_authenticated/admin/role-profiles': typeof AuthenticatedAdminRoleProfilesRoute
  '/_authenticated/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/_authenticated/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/approvals/flows': typeof AuthenticatedApprovalsFlowsRoute
  '/_authenticated/approvals/inbox': typeof AuthenticatedApprovalsInboxRoute
  '/_authenticated/portal/$appId': typeof AuthenticatedPortalAppIdRoute
  '/_authenticated/settings/letter-heads': typeof AuthenticatedSettingsLetterHeadsRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/forms/$tenantId/$formSlug': typeof FormsTenantIdFormSlugRoute
  '/portal/$tenantId/login': typeof PortalTenantIdLoginRoute
  '/portal/$tenantId/my-submissions': typeof PortalTenantIdMySubmissionsRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/apps/$appId/builder': typeof AuthenticatedAppsAppIdBuilderRoute
  '/_authenticated/apps/$appId/flow': typeof AuthenticatedAppsAppIdFlowRoute
  '/_authenticated/apps/$appId/records': typeof AuthenticatedAppsAppIdRecordsRoute
  '/_authenticated/apps/$appId/reports': typeof AuthenticatedAppsAppIdReportsRoute
  '/_authenticated/apps/$appId/scripts': typeof AuthenticatedAppsAppIdScriptsRoute
  '/_authenticated/workflows/runs/$runId': typeof AuthenticatedWorkflowsRunsRunIdRoute
  '/_authenticated/apps/$appId/': typeof AuthenticatedAppsAppIdIndexRoute
  '/_authenticated/workflows/runs/': typeof AuthenticatedWorkflowsRunsIndexRoute
  '/_authenticated/apps/$appId/$modelSlug/records/$recordId': typeof AuthenticatedAppsAppIdModelSlugRecordsRecordIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/ai-builder'
    | '/api-keys'
    | '/billing'
    | '/calendar'
    | '/dashboard'
    | '/desk-chat'
    | '/email-campaigns'
    | '/email-inbox'
    | '/integrations'
    | '/notifications'
    | '/print-formats'
    | '/rules'
    | '/scripts'
    | '/tasks'
    | '/templates'
    | '/workflow-templates'
    | '/admin/ai-config'
    | '/admin/audit-logs'
    | '/admin/backup'
    | '/admin/console'
    | '/admin/error-logs'
    | '/admin/files'
    | '/admin/jobs'
    | '/admin/property-setter'
    | '/admin/rbac'
    | '/admin/request-logs'
    | '/admin/role-profiles'
    | '/admin/tenants'
    | '/admin/usage'
    | '/admin/users'
    | '/approvals/flows'
    | '/approvals/inbox'
    | '/portal/$appId'
    | '/settings/letter-heads'
    | '/settings/profile'
    | '/settings/security'
    | '/forms/$tenantId/$formSlug'
    | '/portal/$tenantId/login'
    | '/portal/$tenantId/my-submissions'
    | '/apps/'
    | '/apps/$appId/builder'
    | '/apps/$appId/flow'
    | '/apps/$appId/records'
    | '/apps/$appId/reports'
    | '/apps/$appId/scripts'
    | '/workflows/runs/$runId'
    | '/apps/$appId/'
    | '/workflows/runs/'
    | '/apps/$appId/$modelSlug/records/$recordId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/ai-builder'
    | '/api-keys'
    | '/billing'
    | '/calendar'
    | '/dashboard'
    | '/desk-chat'
    | '/email-campaigns'
    | '/email-inbox'
    | '/integrations'
    | '/notifications'
    | '/print-formats'
    | '/rules'
    | '/scripts'
    | '/tasks'
    | '/templates'
    | '/workflow-templates'
    | '/admin/ai-config'
    | '/admin/audit-logs'
    | '/admin/backup'
    | '/admin/console'
    | '/admin/error-logs'
    | '/admin/files'
    | '/admin/jobs'
    | '/admin/property-setter'
    | '/admin/rbac'
    | '/admin/request-logs'
    | '/admin/role-profiles'
    | '/admin/tenants'
    | '/admin/usage'
    | '/admin/users'
    | '/approvals/flows'
    | '/approvals/inbox'
    | '/portal/$appId'
    | '/settings/letter-heads'
    | '/settings/profile'
    | '/settings/security'
    | '/forms/$tenantId/$formSlug'
    | '/portal/$tenantId/login'
    | '/portal/$tenantId/my-submissions'
    | '/apps'
    | '/apps/$appId/builder'
    | '/apps/$appId/flow'
    | '/apps/$appId/records'
    | '/apps/$appId/reports'
    | '/apps/$appId/scripts'
    | '/workflows/runs/$runId'
    | '/apps/$appId'
    | '/workflows/runs'
    | '/apps/$appId/$modelSlug/records/$recordId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/_authenticated/ai-builder'
    | '/_authenticated/api-keys'
    | '/_authenticated/billing'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/desk-chat'
    | '/_authenticated/email-campaigns'
    | '/_authenticated/email-inbox'
    | '/_authenticated/integrations'
    | '/_authenticated/notifications'
    | '/_authenticated/print-formats'
    | '/_authenticated/rules'
    | '/_authenticated/scripts'
    | '/_authenticated/tasks'
    | '/_authenticated/templates'
    | '/_authenticated/workflow-templates'
    | '/_authenticated/admin/ai-config'
    | '/_authenticated/admin/audit-logs'
    | '/_authenticated/admin/backup'
    | '/_authenticated/admin/console'
    | '/_authenticated/admin/error-logs'
    | '/_authenticated/admin/files'
    | '/_authenticated/admin/jobs'
    | '/_authenticated/admin/property-setter'
    | '/_authenticated/admin/rbac'
    | '/_authenticated/admin/request-logs'
    | '/_authenticated/admin/role-profiles'
    | '/_authenticated/admin/tenants'
    | '/_authenticated/admin/usage'
    | '/_authenticated/admin/users'
    | '/_authenticated/approvals/flows'
    | '/_authenticated/approvals/inbox'
    | '/_authenticated/portal/$appId'
    | '/_authenticated/settings/letter-heads'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/security'
    | '/forms/$tenantId/$formSlug'
    | '/portal/$tenantId/login'
    | '/portal/$tenantId/my-submissions'
    | '/_authenticated/apps/'
    | '/_authenticated/apps/$appId/builder'
    | '/_authenticated/apps/$appId/flow'
    | '/_authenticated/apps/$appId/records'
    | '/_authenticated/apps/$appId/reports'
    | '/_authenticated/apps/$appId/scripts'
    | '/_authenticated/workflows/runs/$runId'
    | '/_authenticated/apps/$appId/'
    | '/_authenticated/workflows/runs/'
    | '/_authenticated/apps/$appId/$modelSlug/records/$recordId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  FormsTenantIdFormSlugRoute: typeof FormsTenantIdFormSlugRoute
  PortalTenantIdLoginRoute: typeof PortalTenantIdLoginRoute
  PortalTenantIdMySubmissionsRoute: typeof PortalTenantIdMySubmissionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workflow-templates': {
      id: '/_authenticated/workflow-templates'
      path: '/workflow-templates'
      fullPath: '/workflow-templates'
      preLoaderRoute: typeof AuthenticatedWorkflowTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scripts': {
      id: '/_authenticated/scripts'
      path: '/scripts'
      fullPath: '/scripts'
      preLoaderRoute: typeof AuthenticatedScriptsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rules': {
      id: '/_authenticated/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AuthenticatedRulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/print-formats': {
      id: '/_authenticated/print-formats'
      path: '/print-formats'
      fullPath: '/print-formats'
      preLoaderRoute: typeof AuthenticatedPrintFormatsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/email-inbox': {
      id: '/_authenticated/email-inbox'
      path: '/email-inbox'
      fullPath: '/email-inbox'
      preLoaderRoute: typeof AuthenticatedEmailInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/email-campaigns': {
      id: '/_authenticated/email-campaigns'
      path: '/email-campaigns'
      fullPath: '/email-campaigns'
      preLoaderRoute: typeof AuthenticatedEmailCampaignsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/desk-chat': {
      id: '/_authenticated/desk-chat'
      path: '/desk-chat'
      fullPath: '/desk-chat'
      preLoaderRoute: typeof AuthenticatedDeskChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/api-keys': {
      id: '/_authenticated/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AuthenticatedApiKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-builder': {
      id: '/_authenticated/ai-builder'
      path: '/ai-builder'
      fullPath: '/ai-builder'
      preLoaderRoute: typeof AuthenticatedAiBuilderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/portal/$tenantId/my-submissions': {
      id: '/portal/$tenantId/my-submissions'
      path: '/portal/$tenantId/my-submissions'
      fullPath: '/portal/$tenantId/my-submissions'
      preLoaderRoute: typeof PortalTenantIdMySubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$tenantId/login': {
      id: '/portal/$tenantId/login'
      path: '/portal/$tenantId/login'
      fullPath: '/portal/$tenantId/login'
      preLoaderRoute: typeof PortalTenantIdLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$tenantId/$formSlug': {
      id: '/forms/$tenantId/$formSlug'
      path: '/forms/$tenantId/$formSlug'
      fullPath: '/forms/$tenantId/$formSlug'
      preLoaderRoute: typeof FormsTenantIdFormSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/letter-heads': {
      id: '/_authenticated/settings/letter-heads'
      path: '/settings/letter-heads'
      fullPath: '/settings/letter-heads'
      preLoaderRoute: typeof AuthenticatedSettingsLetterHeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/$appId': {
      id: '/_authenticated/portal/$appId'
      path: '/portal/$appId'
      fullPath: '/portal/$appId'
      preLoaderRoute: typeof AuthenticatedPortalAppIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/approvals/inbox': {
      id: '/_authenticated/approvals/inbox'
      path: '/approvals/inbox'
      fullPath: '/approvals/inbox'
      preLoaderRoute: typeof AuthenticatedApprovalsInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/approvals/flows': {
      id: '/_authenticated/approvals/flows'
      path: '/approvals/flows'
      fullPath: '/approvals/flows'
      preLoaderRoute: typeof AuthenticatedApprovalsFlowsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/usage': {
      id: '/_authenticated/admin/usage'
      path: '/admin/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AuthenticatedAdminUsageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/tenants': {
      id: '/_authenticated/admin/tenants'
      path: '/admin/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AuthenticatedAdminTenantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/role-profiles': {
      id: '/_authenticated/admin/role-profiles'
      path: '/admin/role-profiles'
      fullPath: '/admin/role-profiles'
      preLoaderRoute: typeof AuthenticatedAdminRoleProfilesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/request-logs': {
      id: '/_authenticated/admin/request-logs'
      path: '/admin/request-logs'
      fullPath: '/admin/request-logs'
      preLoaderRoute: typeof AuthenticatedAdminRequestLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/rbac': {
      id: '/_authenticated/admin/rbac'
      path: '/admin/rbac'
      fullPath: '/admin/rbac'
      preLoaderRoute: typeof AuthenticatedAdminRbacRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/property-setter': {
      id: '/_authenticated/admin/property-setter'
      path: '/admin/property-setter'
      fullPath: '/admin/property-setter'
      preLoaderRoute: typeof AuthenticatedAdminPropertySetterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/jobs': {
      id: '/_authenticated/admin/jobs'
      path: '/admin/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AuthenticatedAdminJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/files': {
      id: '/_authenticated/admin/files'
      path: '/admin/files'
      fullPath: '/admin/files'
      preLoaderRoute: typeof AuthenticatedAdminFilesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/error-logs': {
      id: '/_authenticated/admin/error-logs'
      path: '/admin/error-logs'
      fullPath: '/admin/error-logs'
      preLoaderRoute: typeof AuthenticatedAdminErrorLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/console': {
      id: '/_authenticated/admin/console'
      path: '/admin/console'
      fullPath: '/admin/console'
      preLoaderRoute: typeof AuthenticatedAdminConsoleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/backup': {
      id: '/_authenticated/admin/backup'
      path: '/admin/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AuthenticatedAdminBackupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/audit-logs': {
      id: '/_authenticated/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/ai-config': {
      id: '/_authenticated/admin/ai-config'
      path: '/admin/ai-config'
      fullPath: '/admin/ai-config'
      preLoaderRoute: typeof AuthenticatedAdminAiConfigRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workflows/runs/': {
      id: '/_authenticated/workflows/runs/'
      path: '/workflows/runs'
      fullPath: '/workflows/runs/'
      preLoaderRoute: typeof AuthenticatedWorkflowsRunsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/$appId/': {
      id: '/_authenticated/apps/$appId/'
      path: '/apps/$appId'
      fullPath: '/apps/$appId/'
      preLoaderRoute: typeof AuthenticatedAppsAppIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workflows/runs/$runId': {
      id: '/_authenticated/workflows/runs/$runId'
      path: '/workflows/runs/$runId'
      fullPath: '/workflows/runs/$runId'
      preLoaderRoute: typeof AuthenticatedWorkflowsRunsRunIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/$appId/scripts': {
      id: '/_authenticated/apps/$appId/scripts'
      path: '/apps/$appId/scripts'
      fullPath: '/apps/$appId/scripts'
      preLoaderRoute: typeof AuthenticatedAppsAppIdScriptsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/$appId/reports': {
      id: '/_authenticated/apps/$appId/reports'
      path: '/apps/$appId/reports'
      fullPath: '/apps/$appId/reports'
      preLoaderRoute: typeof AuthenticatedAppsAppIdReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/$appId/records': {
      id: '/_authenticated/apps/$appId/records'
      path: '/apps/$appId/records'
      fullPath: '/apps/$appId/records'
      preLoaderRoute: typeof AuthenticatedAppsAppIdRecordsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/$appId/flow': {
      id: '/_authenticated/apps/$appId/flow'
      path: '/apps/$appId/flow'
      fullPath: '/apps/$appId/flow'
      preLoaderRoute: typeof AuthenticatedAppsAppIdFlowRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/$appId/builder': {
      id: '/_authenticated/apps/$appId/builder'
      path: '/apps/$appId/builder'
      fullPath: '/apps/$appId/builder'
      preLoaderRoute: typeof AuthenticatedAppsAppIdBuilderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/$appId/$modelSlug/records/$recordId': {
      id: '/_authenticated/apps/$appId/$modelSlug/records/$recordId'
      path: '/apps/$appId/$modelSlug/records/$recordId'
      fullPath: '/apps/$appId/$modelSlug/records/$recordId'
      preLoaderRoute: typeof AuthenticatedAppsAppIdModelSlugRecordsRecordIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAiBuilderRoute: typeof AuthenticatedAiBuilderRoute
  AuthenticatedApiKeysRoute: typeof AuthenticatedApiKeysRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeskChatRoute: typeof AuthenticatedDeskChatRoute
  AuthenticatedEmailCampaignsRoute: typeof AuthenticatedEmailCampaignsRoute
  AuthenticatedEmailInboxRoute: typeof AuthenticatedEmailInboxRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPrintFormatsRoute: typeof AuthenticatedPrintFormatsRoute
  AuthenticatedRulesRoute: typeof AuthenticatedRulesRoute
  AuthenticatedScriptsRoute: typeof AuthenticatedScriptsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedWorkflowTemplatesRoute: typeof AuthenticatedWorkflowTemplatesRoute
  AuthenticatedAdminAiConfigRoute: typeof AuthenticatedAdminAiConfigRoute
  AuthenticatedAdminAuditLogsRoute: typeof AuthenticatedAdminAuditLogsRoute
  AuthenticatedAdminBackupRoute: typeof AuthenticatedAdminBackupRoute
  AuthenticatedAdminConsoleRoute: typeof AuthenticatedAdminConsoleRoute
  AuthenticatedAdminErrorLogsRoute: typeof AuthenticatedAdminErrorLogsRoute
  AuthenticatedAdminFilesRoute: typeof AuthenticatedAdminFilesRoute
  AuthenticatedAdminJobsRoute: typeof AuthenticatedAdminJobsRoute
  AuthenticatedAdminPropertySetterRoute: typeof AuthenticatedAdminPropertySetterRoute
  AuthenticatedAdminRbacRoute: typeof AuthenticatedAdminRbacRoute
  AuthenticatedAdminRequestLogsRoute: typeof AuthenticatedAdminRequestLogsRoute
  AuthenticatedAdminRoleProfilesRoute: typeof AuthenticatedAdminRoleProfilesRoute
  AuthenticatedAdminTenantsRoute: typeof AuthenticatedAdminTenantsRoute
  AuthenticatedAdminUsageRoute: typeof AuthenticatedAdminUsageRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedApprovalsFlowsRoute: typeof AuthenticatedApprovalsFlowsRoute
  AuthenticatedApprovalsInboxRoute: typeof AuthenticatedApprovalsInboxRoute
  AuthenticatedPortalAppIdRoute: typeof AuthenticatedPortalAppIdRoute
  AuthenticatedSettingsLetterHeadsRoute: typeof AuthenticatedSettingsLetterHeadsRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedAppsAppIdBuilderRoute: typeof AuthenticatedAppsAppIdBuilderRoute
  AuthenticatedAppsAppIdFlowRoute: typeof AuthenticatedAppsAppIdFlowRoute
  AuthenticatedAppsAppIdRecordsRoute: typeof AuthenticatedAppsAppIdRecordsRoute
  AuthenticatedAppsAppIdReportsRoute: typeof AuthenticatedAppsAppIdReportsRoute
  AuthenticatedAppsAppIdScriptsRoute: typeof AuthenticatedAppsAppIdScriptsRoute
  AuthenticatedWorkflowsRunsRunIdRoute: typeof AuthenticatedWorkflowsRunsRunIdRoute
  AuthenticatedAppsAppIdIndexRoute: typeof AuthenticatedAppsAppIdIndexRoute
  AuthenticatedWorkflowsRunsIndexRoute: typeof AuthenticatedWorkflowsRunsIndexRoute
  AuthenticatedAppsAppIdModelSlugRecordsRecordIdRoute: typeof AuthenticatedAppsAppIdModelSlugRecordsRecordIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAiBuilderRoute: AuthenticatedAiBuilderRoute,
  AuthenticatedApiKeysRoute: AuthenticatedApiKeysRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeskChatRoute: AuthenticatedDeskChatRoute,
  AuthenticatedEmailCampaignsRoute: AuthenticatedEmailCampaignsRoute,
  AuthenticatedEmailInboxRoute: AuthenticatedEmailInboxRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPrintFormatsRoute: AuthenticatedPrintFormatsRoute,
  AuthenticatedRulesRoute: AuthenticatedRulesRoute,
  AuthenticatedScriptsRoute: AuthenticatedScriptsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedWorkflowTemplatesRoute: AuthenticatedWorkflowTemplatesRoute,
  AuthenticatedAdminAiConfigRoute: AuthenticatedAdminAiConfigRoute,
  AuthenticatedAdminAuditLogsRoute: AuthenticatedAdminAuditLogsRoute,
  AuthenticatedAdminBackupRoute: AuthenticatedAdminBackupRoute,
  AuthenticatedAdminConsoleRoute: AuthenticatedAdminConsoleRoute,
  AuthenticatedAdminErrorLogsRoute: AuthenticatedAdminErrorLogsRoute,
  AuthenticatedAdminFilesRoute: AuthenticatedAdminFilesRoute,
  AuthenticatedAdminJobsRoute: AuthenticatedAdminJobsRoute,
  AuthenticatedAdminPropertySetterRoute: AuthenticatedAdminPropertySetterRoute,
  AuthenticatedAdminRbacRoute: AuthenticatedAdminRbacRoute,
  AuthenticatedAdminRequestLogsRoute: AuthenticatedAdminRequestLogsRoute,
  AuthenticatedAdminRoleProfilesRoute: AuthenticatedAdminRoleProfilesRoute,
  AuthenticatedAdminTenantsRoute: AuthenticatedAdminTenantsRoute,
  AuthenticatedAdminUsageRoute: AuthenticatedAdminUsageRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedApprovalsFlowsRoute: AuthenticatedApprovalsFlowsRoute,
  AuthenticatedApprovalsInboxRoute: AuthenticatedApprovalsInboxRoute,
  AuthenticatedPortalAppIdRoute: AuthenticatedPortalAppIdRoute,
  AuthenticatedSettingsLetterHeadsRoute: AuthenticatedSettingsLetterHeadsRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedAppsAppIdBuilderRoute: AuthenticatedAppsAppIdBuilderRoute,
  AuthenticatedAppsAppIdFlowRoute: AuthenticatedAppsAppIdFlowRoute,
  AuthenticatedAppsAppIdRecordsRoute: AuthenticatedAppsAppIdRecordsRoute,
  AuthenticatedAppsAppIdReportsRoute: AuthenticatedAppsAppIdReportsRoute,
  AuthenticatedAppsAppIdScriptsRoute: AuthenticatedAppsAppIdScriptsRoute,
  AuthenticatedWorkflowsRunsRunIdRoute: AuthenticatedWorkflowsRunsRunIdRoute,
  AuthenticatedAppsAppIdIndexRoute: AuthenticatedAppsAppIdIndexRoute,
  AuthenticatedWorkflowsRunsIndexRoute: AuthenticatedWorkflowsRunsIndexRoute,
  AuthenticatedAppsAppIdModelSlugRecordsRecordIdRoute:
    AuthenticatedAppsAppIdModelSlugRecordsRecordIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  FormsTenantIdFormSlugRoute: FormsTenantIdFormSlugRoute,
  PortalTenantIdLoginRoute: PortalTenantIdLoginRoute,
  PortalTenantIdMySubmissionsRoute: PortalTenantIdMySubmissionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
